/*
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2018-01-16   Mendel Guillaume       Created
   ========+============+=================+===============================================
*/

public interface LightningInnerClass
{
	// empty interface to allow for using inner class as component attributes. 
}